# Generated by Django 4.2.13 on 2024-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwaredevelopmentapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='projectid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
